export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_MOVIES_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const LOAD_BEST_MOVIES_SUCCESS = 'LOAD_BEST_MOVIES_SUCCESS';
export const LOAD_DISCOVERED_MOVIES_SUCCESS = 'LOAD_DISCOVERED_MOVIES_SUCCESS';

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

