export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_MOVIES_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';
export const LOAD_BEST_MOVIES_SUCCESS = 'LOAD_BEST_MOVIES_SUCCESS';
export const LOAD_DISCOVERED_MOVIES_SUCCESS = 'LOAD_DISCOVERED_MOVIES_SUCCESS';

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

// States for login process
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// States for logout process
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'